language: elixir

otp_release:
  - 18.0
  - 19.0
elixir:
  - 1.3.1

env:
  - MIX_ENV=test
script:
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix compile --warnings-as-errors
  - mix test
  - mix credo --strict
